<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include=".vs\UserRoles\v17\DocumentLayout.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".vs\UserRoles\config\applicationhost.config" />
    <None Include=".vs\UserRoles\CopilotIndices\17.14.1368.60722\CodeChunks.db" />
    <None Include=".vs\UserRoles\CopilotIndices\17.14.1368.60722\CodeChunks.db-shm" />
    <None Include=".vs\UserRoles\CopilotIndices\17.14.1368.60722\CodeChunks.db-wal" />
    <None Include=".vs\UserRoles\CopilotIndices\17.14.1368.60722\SemanticSymbols.db" />
    <None Include=".vs\UserRoles\CopilotIndices\17.14.1368.60722\SemanticSymbols.db-shm" />
    <None Include=".vs\UserRoles\CopilotIndices\17.14.1368.60722\SemanticSymbols.db-wal" />
    <None Include=".vs\UserRoles\FileContentIndex\f3fd3e40-fcaf-4476-a62b-3093d3802617.vsidx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
